import{g as v}from"./assets/scroll-up-D7sVMKBY.js";import"./assets/vendor-DdHXTJIf.js";document.addEventListener("DOMContentLoaded",()=>{const a=document.getElementById("categories-grid"),s=document.getElementById("exercises-fallback"),c=document.getElementById("exercises-category-title"),d=document.getElementById("exercises-title-divider"),n=document.getElementById("exercises-search-form"),o=document.getElementById("categories-container"),l=document.getElementById("exercises-grid-container"),m=document.querySelectorAll(".tabs-btn");let g="Muscles",f=1;const L=window.innerWidth>=1440?12:8;u(),m.forEach(i=>{i.addEventListener("click",t=>{const r=t.currentTarget;r.classList.contains("active")||(m.forEach(e=>e.classList.remove("active")),r.classList.add("active"),g=r.getAttribute("data-filter")||"Muscles",f=1,c&&c.classList.add("is-hidden"),d&&d.classList.add("is-hidden"),o&&o.classList.remove("is-hidden"),l&&l.classList.add("is-hidden"),n&&(g==="Body parts"?n.classList.remove("is-hidden"):n.classList.add("is-hidden")),u())})});async function u(){if(a){a.innerHTML='<div class="loader"></div>',s&&s.classList.add("is-hidden");try{const i=await v(g,f,L),{results:t,totalPages:r}=i.data;if(!t||t.length===0){a.innerHTML="",s&&s.classList.remove("is-hidden");return}a.innerHTML=t.map(e=>`
        <li class="category-card" data-category="${e.name}" data-filter="${e.filter}">
          <img class="category-card-img" src="${e.imgURL}" alt="${e.name}" loading="lazy" />
          <div class="category-card-overlay"></div>
          <div class="category-card-content">
            <h3 class="category-card-name">${e.name}</h3>
            <p class="category-card-filter">${e.filter}</p>
          </div>
        </li>
      `).join(""),h()}catch(i){console.error("Error loading categories:",i),a.innerHTML="",s&&s.classList.remove("is-hidden")}}}function h(){document.querySelectorAll(".category-card").forEach(t=>{t.addEventListener("click",r=>{const y=r.currentTarget.getAttribute("data-category");o&&o.classList.add("is-hidden"),l&&l.classList.remove("is-hidden"),c&&y&&(c.textContent=y,c.classList.remove("is-hidden")),d&&d.classList.remove("is-hidden"),n&&n.classList.remove("is-hidden")})})}});console.log("Your Energy app initialized");
//# sourceMappingURL=index.js.map
